### PR TITLE
Online

### PR DESCRIPTION
**Pull request by Fengwangdong**
This is the modified and updated JRA package for HLT JECs.

### CODE REVIEW

**Comment by aperloff** [comment]
Feng, This pull request would overwrite a lot of the updates we've made to the code. I think you first need to rebase your version of the code to be in sync with the master branch of cms-jet/JetMETAnalysis. This will then apply all of your changes on top. This will allow me to see exactly what you have changed (as opposed to this mash of your changes and some old code). If none of your changes conflict, only adding functionality and not subtracting it or harming it, then we are okay. Does this make sense to you?

**Comment by Fengwangdong** [comment]
Alexx, you are right. I need to use the same files as in the latest framework, and only change the files that I've modified for online case. According to my previous experience, there are some scripts that cannot be compatible in online and offline cases at the same time. If that, we can only keep them in different branches instead of synchronizing them.

**Comment by aperloff** [comment]
Feng, can you tell me which scripts are not compatible and why? Keeping two
branches is possible, but involves way more overhead (according to some Git
gurus here at FNAL). It might be possible for us to integrate all the good
work you¹ve been doing into the rest of the framework without losing any
functionality. I¹m happy to work with you to achieve this goal.


From:  fengwang <notifications@github.com>
Reply-To:  cms-jet/JetMETAnalysis
<reply+00495daa00c450a88ac19350df1572115be253013892ad9d92cf0000000112e6f74d9
2a169ce081e1cbf@reply.github.com>
Date:  Thursday, February 25, 2016 at 11:09 AM
To:  cms-jet/JetMETAnalysis <JetMETAnalysis@noreply.github.com>
Cc:  Alexx Perloff <aperloff@physics.tamu.edu>
Subject:  Re: [JetMETAnalysis] Online (#7)


Alexx, you are right. I need to use the same files as in the latest
framework, and only change the files that I've modified for online case.
According to my previous experience, there are some scripts that cannot be
compatible in online and offline cases at the same time. If that, we can
only keep them in different branches instead of synchronizing them.


Reply to this email directly or view it on GitHub
<https://github.com/cms-jet/JetMETAnalysis/pull/7#issuecomment-188881748> .

**Comment by Fengwangdong** [comment]
Alexx, It was according to my previous comparison (last year), but I don't remember which one exactly at the moment. Now I need some time to compare my latest modified files and your newest files, and I will keep you informed after I recheck them. Actually I'm also looking forward to realize this aim with you together;)

**Comment by aperloff** [comment]
Hi Feng. Okay, I will await your comparison. Just let me know when you want
me to take a look again.


From:  fengwang <notifications@github.com>
Reply-To:  cms-jet/JetMETAnalysis
<reply+00495daaad4090e8a13fa43806a84ac05d36a0f6798908f192cf0000000112e7075c9
2a169ce081e1cbf@reply.github.com>
Date:  Thursday, February 25, 2016 at 12:18 PM
To:  cms-jet/JetMETAnalysis <JetMETAnalysis@noreply.github.com>
Cc:  Alexx Perloff <aperloff@physics.tamu.edu>
Subject:  Re: [JetMETAnalysis] Online (#7)


Alexx, It was according to my previous comparison (last year), but I don't
remember which one exactly at the moment. Now I need some time to compare my
latest modified files and your newest files, and I will keep you informed
after I recheck them. Actually I'm also looking forward to realize this aim
with you together;)


Reply to this email directly or view it on GitHub
<https://github.com/cms-jet/JetMETAnalysis/pull/7#issuecomment-188916329> .

**Pull request closed without merging**
